### ISSUE TITLE
Doesn't work with Godot 3.0

### ISSUE THREAD

**Issue by Zireael07** [Zylann/godot_fastnoise#1]
Probably needs the same treatment as the open simplex got.

**Comment by Zylann** [comment]
I just updated the code

**Comment by Xrayez** [comment]
Zylann's changes were necessary but there is one issue that scons doesn't seem to support `SCONS_CXX_STANDARD` environ variable so I couldn't compile the module either.

**Comment by Zylann** [comment]
Which line is the compiler complaining about?

**Comment by Xrayez** [comment]
```
In file included from modules/fastnoise/lib/FastNoise.cpp:29:0:
modules/fastnoise/lib/FastNoise.h:133:37: error: 'nullptr' was not declared in this scope
  FastNoise* m_cellularNoiseLookup = nullptr;
                                     ^
[ 14%] modules/fastnoise/lib/FastNoise.cpp: In member function 'float fastnoise::FastNoise::GetNoise(float, float, float)':
modules/fastnoise/lib/FastNoise.cpp:254:18: error: 'fastnoise::FastNoise::NoiseType' is not a class or namespace
  case FastNoise::NoiseType::Value:
```

This error repeats for other NoiseType's aswell

**Comment by Zylann** [comment]
Oh, right. I should have used NULL here, since I don't use any C++11 feature besides that (Godot core uses old C++03), but choosing C++11 would also fix it because modules can have different compilation flags... not sure which option is best.

**Comment by Xrayez** [comment]
I was thinking about it too and I'm not sure either. It's up to you, my pull request is there if you decide to keep C++11.
